# Load user specific variables and API KEYS
[[ -s "$HOME/dotfiles/.user_variables" ]] && source "$HOME/dotfiles/.user_variables"

# Load Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# Load asdf
. /opt/homebrew/opt/asdf/libexec/asdf.sh

# Configure base16 colorscheme
BASE16_SHELL="$HOME/dotfiles/addons/base16-shell/"
[ -n "$PS1" ] && [ -s "$BASE16_SHELL/profile_helper.sh" ] && eval "$("$BASE16_SHELL/profile_helper.sh")"

# Load environment variables for development
[[ -s "$HOME/.environment_variables" ]] && source "$HOME/.environment_variables"

# Load terminal prompt scripts
[[ -s "$HOME/.bash_prompt" ]] && source "$HOME/.bash_prompt"

# Load aliases
[[ -s "$HOME/.aliases" ]] && source "$HOME/.aliases"

# Load homebrew completions
HOMEBREW_PREFIX=$(brew --prefix)
if type brew &>/dev/null; then
  for COMPLETION in "$HOMEBREW_PREFIX"/etc/bash_completion.d/*
  do
    [[ -f $COMPLETION ]] && source "$COMPLETION"
  done
  if [[ -f ${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh ]];
  then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  fi

  __git_complete g __git_main
fi
