# Load user specific variables and API KEYS
[[ -s "$HOME/dotfiles/.user_variables" ]] && source "$HOME/dotfiles/.user_variables"

# Append Homebrew path before system bin
[[ -s "$HOME/.bash_path" ]] && source "$HOME/.bash_path"

# Load rbenv
if which rbenv > /dev/null; then
  eval "$(rbenv init -)"
fi

# Load nodenv
if which nodenv > /dev/null; then
  eval "$(nodenv init -)"
fi

# Load pyenv
if which pyenv > /dev/null; then
  eval "$(pyenv init -)"
fi

# Load jenv
if which jenv > /dev/null; then
  eval "$(jenv init -)"
fi

# Load direnv
if type "direnv" &> /dev/null; then
  eval "$(direnv hook bash)"
fi

# Configure base16 colorscheme
BASE16_SHELL="$HOME/dotfiles/addons/base16-shell/"
[ -n "$PS1" ] && [ -s "$BASE16_SHELL/profile_helper.sh" ] && eval "$("$BASE16_SHELL/profile_helper.sh")"

# Load environment variables for development
[[ -s "$HOME/.environment_variables" ]] && source "$HOME/.environment_variables"

# Load terminal prompt scripts
[[ -s "$HOME/.bash_prompt" ]] && source "$HOME/.bash_prompt"

# Load aliases
[[ -s "$HOME/.aliases" ]] && source "$HOME/.aliases"

# Load homebrew completions
HOMEBREW_PREFIX=$(brew --prefix)
if type brew &>/dev/null; then
  for COMPLETION in "$HOMEBREW_PREFIX"/etc/bash_completion.d/*
  do
    [[ -f $COMPLETION ]] && source "$COMPLETION"
  done
  if [[ -f ${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh ]];
  then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  fi
fi
