# Load user specific variables and API KEYS
[[ -s "$HOME/dotfiles/.user_variables" ]] && source "$HOME/dotfiles/.user_variables"

# Append Homebrew path before system bin
[[ -s "$HOME/.bash_path" ]] && source "$HOME/.bash_path"

# Load RVM into a shell session *as a function*
if which rvm > /dev/null; then
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
fi

# Load rbenv
if which rbenv > /dev/null; then
  eval "$(rbenv init -)"
fi

# This loads NVM
[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh

# Load environment variables for development
[[ -s "$HOME/.environment_variables" ]] && source "$HOME/.environment_variables"

# Load terminal prompt scripts
[[ -s "$HOME/.bash_prompt" ]] && source "$HOME/.bash_prompt"

# Load aliases
[[ -s "$HOME/.aliases" ]] && source "$HOME/.aliases"

# Use Homebrew bash completion
if type "brew" &> /dev/null && [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

if type "direnv" &> /dev/null; then
  eval "$(direnv hook bash)"
fi

